# Generated by Django 4.0.5 on 2022-06-13 23:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GZModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('logits', models.FloatField()),
                ('net_sent', models.FloatField()),
                ('logits_mean', models.FloatField()),
                ('net_sent_mean', models.FloatField()),
                ('MA_logits', models.FloatField()),
                ('MA_net_sent', models.FloatField()),
                ('MA_net_sent_ema_alpha_0_1', models.FloatField()),
                ('MA_net_sent_ema_alpha_0_3', models.FloatField()),
                ('MA_net_sent_ema_alpha_0_5', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='YPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('sentence', models.TextField()),
                ('sentence_short', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
                ('sentence_keywords', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=2), default=list, size=None)),
                ('sentence_sentiment', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=2)),
                ('sentence_sentiment_net', models.FloatField()),
                ('sentence_sent_score', models.FloatField()),
                ('sentence_sentiment_label', models.IntegerField(choices=[(1, 'True'), (1, 'False')])),
                ('sentence_entities', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=2), default=list, size=None)),
                ('sentence_non_entities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
            ],
        ),
    ]
